# Generated by Django 3.1.6 on 2021-04-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='allimg')),
                ('date', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
