# Generated by Django 3.1.6 on 2021-06-01 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='files',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents'),
            preserve_default=False,
        ),
    ]
